type game_.js > game.js
type game_sprite.js >> game.js
type game_player.js >> game.js
type game_enemies.js >> game.js
type game_enemy.js >> game.js
type game_enemy2.js >> game.js
type game_bucket.js >> game.js
type game_game.js >> game.js
type game_dirt.js >> game.js
type game_gui.js >> game.js